import fs from "node:fs";
import path from "node:path";

const publicDir = path.resolve(process.cwd(), "public");
const cache = new Map<string, boolean>();

/**
 * Rewrites an /attachments raster URL to its .avif sibling when one was
 * generated by scripts/optimize-images.mjs. Falls back to the original
 * URL (and original file) when no .avif exists.
 */
export function toAvif(url: string): string {
  const m = url.match(/^(\/?)(attachments\/.+)\.(jpe?g|png)$/i);
  if (!m) return url;

  let rel = `${m[2]}.avif`;
  try {
    rel = decodeURIComponent(rel);
  } catch {
    // keep raw path if it isn't valid percent-encoding
  }

  let exists = cache.get(rel);
  if (exists === undefined) {
    exists = fs.existsSync(path.join(publicDir, rel));
    cache.set(rel, exists);
  }
  return exists ? url.replace(/\.(jpe?g|png)$/i, ".avif") : url;
}
